// 霸都丶傲天 2019年10月10日 https://github.com/AJLoveChina/birthday
var config = {
    // 句子的长度可以任意， 你可以写十句话， 二十句话都可以
    // 每句话尽量不要超过15个字,不然展示效果可能不太好
    texts: [
        "2020.06.07",      //这里,每句话结尾的最后一个逗号必须是英文的哦!! 很重要哦!!
        "我驕傲的公主呀",  // 同上...
        "對不起我來遲了",
        "今天是寶貝的生日",
        "很開心我的寶貝又長大了",
        "更加的成熟 更加的美麗了",
        "三生有幸遇見了",
        "我心愛的寶貝",
        "已經錯過了寶貝21年的成長",
        "以後的生日",
        "我都會陪寶貝一起過",
        "我要和寶貝一同",
        "享受時光的流逝",
        "直到有一天",
        "慕然回首 突然發現",
        "我們已經滿頭白髮",
        "不禁的笑了出來",
        "嘴裏卻不見了牙齒",
        "可我們依舊是",
        "從前的我們 如今的我們",
        "執子之手 與子偕老",
        "不負此生",
        "我們的相遇與赤心",
        "I would share my sadness with you.",
        "But just a little.",
        "I prefer to share my happiness with you.",
        "Even wish you could feel happy as I felt.",
        "我願用先前的積纍 學習",
        "與餘生的努力 奮鬥",
        "去創造屬於我們的美好",
        "我可愛的傻豬豬呀",
        "不要抱怨 嫌棄我的嘮叨",
        "這份特殊的愛",
        "是只屬於你的",
        "祝我家的豬豬",
        "在新的一年裏",
        "吃好睡好 無憂無慮",
        "養的白白胖胖的",
        "最後 我再把你抱走",
        "哈~哈~哈",
        "我希望我的寶貝",
        "永遠不要長大",
        "永遠這樣 純真善良無瑕",
        "像陽光一樣 溫暖開心",
        "像小鳥一樣 快樂瘋狂",
        "我要你自私地活下去",
        "永不受 人情冷暖 流言蜚語",
        "我要你 平安喜樂 得償所願",
        "我的女孩啊 生日快樂!",
    ],
    /**
     */
    imgs: {
        "我的女孩啊 生日快樂!": "./imgs/d.png",
        "今天是寶貝的生日": "./imgs/d.png",
        "很開心我的寶貝又長大了": "./imgs/d.png",
        "更加的成熟 更加的美麗了": "./imgs/d.png",
        "三生有幸遇見了": "./imgs/d.png",
        "我心愛的寶貝": "./imgs/d.png",
        "已經錯過了寶貝21年的成長": "./imgs/d.png",
        "以後的生日": "./imgs/d.png",
        "我都會陪寶貝一起過": "./imgs/d.png",
        "我要和寶貝一同": "./imgs/d.png",
        "享受時光的流逝": "./imgs/d.png",
        "直到有一天": "./imgs/d.png",
        "慕然回首 突然發現": "./imgs/d.png",
        "我們已經滿頭白髮": "./imgs/d.png",
        "不禁的笑了出來": "./imgs/d.png",
        "嘴裏卻不見了牙齒": "./imgs/d.png",
        "可我們依舊是": "./imgs/d.png",
        "從前的我們 如今的我們": "./imgs/d.png",
        "執子之手 與子偕老": "./imgs/d.png",
        "不負此生": "./imgs/d.png",
        "我們的相遇與赤心": "./imgs/d.png",
        "I would share my sadness with you": "./imgs/d.png",
        "But just a little.": "./imgs/d.png",
        "I prefer to share my happiness with you.": "./imgs/d.png",
        "Even wish you could feel happy as I felt.": "./imgs/d.png",
        "我願用先前的積纍 學習": "./imgs/d.png",
        "與餘生的努力 奮鬥": "./imgs/d.png",
        "去創造屬於我們的美好": "./imgs/d.png",
        "我可愛的傻豬豬呀": "./imgs/d.png",
        "不要抱怨 嫌棄我的嘮叨": "./imgs/d.png",
        "這份特殊的愛": "./imgs/d.png",
        "是只屬於你的": "./imgs/d.png",
        "祝我家的豬豬": "./imgs/d.png",
        "在新的一年裏": "./imgs/d.png",
        "吃好睡好 無憂無慮": "./imgs/d.png",
        "養的白白胖胖的": "./imgs/d.png",
        "最後 我再把你抱走": "./imgs/d.png",
        "哈~哈~哈": "./imgs/d.png",
        "我希望我的寶貝": "./imgs/d.png",
        "永遠不要長大": "./imgs/d.png",
        "永遠這樣 純真善良無瑕": "./imgs/d.png",
        "像陽光一樣 溫暖開心": "./imgs/d.png",
        "像小鳥一樣 快樂瘋狂": "./imgs/d.png",
        "我要你自私地活下去"
        "永不受 人情冷暖 流言蜚語": "./imgs/d.png",
        "我要你 平安喜樂 得償所願": "./imgs/d.png",
        "我的女孩啊 生日快樂!": "./imgs/d.png",
    },
    // 按钮文字描述, 以下是默认的按钮文字，英文的，您可以改成你喜欢的文字
    desc: {
        turn_on: "這是什麽直男玩意兒",
        play: "這麽安靜 真無聊",
        bannar_coming: "一張圖片真沒創意",
        balloons_flying: "果然是沒有情調的男人",
        cake_fadein: "好想~好想吃蛋糕呀",
        light_candle: "我要偷偷許個願望",
        wish_message: "happy birthday",
        story: "A MESSAGE FOR YOU",
    }
};
